In [1]:
import numpy as np

In [66]:
xs = np.tile(np.arange(0, 8).reshape((-1, 1)), (1, 2))
xs = np.stack([xs] * 3, axis=0) * np.array([1, 10, 100])[:, None, None]
N, T, nx = xs.shape

In [67]:
xcurr = np.reshape(xs[:, :-1, :], (N * (T - 1), nx))
xnext = np.reshape(xs[:, 1:, :], (N * (T - 1), nx))

In [68]:
print(xs.reshape(-1, nx))

[[  0   0]
 [  1   1]
 [  2   2]
 [  3   3]
 [  4   4]
 [  5   5]
 [  6   6]
 [  7   7]
 [  0   0]
 [ 10  10]
 [ 20  20]
 [ 30  30]
 [ 40  40]
 [ 50  50]
 [ 60  60]
 [ 70  70]
 [  0   0]
 [100 100]
 [200 200]
 [300 300]
 [400 400]
 [500 500]
 [600 600]
 [700 700]]


In [52]:
xs2 = np.array([[1, 2, 3],
                [4, 5, 6]])
us = np.array([[1, 10],
               [3, 7]])

def kronecker_rows(XS, US):
    """
    XS: (B, nx)
    US: (B, nu)
    Returns: (B, nx * nu)
    """
    B, nx = XS.shape
    _, nu = US.shape

    # Expand dimensions to broadcast
    XS_expanded = XS[:, np.newaxis, :]     # (B, 1, nx)
    US_expanded = US[:, :, np.newaxis]     # (B, nu, 1)

    # Elementwise multiply (B, nu, nx)
    result = US_expanded * XS_expanded

    # Reshape to (B, nu * nx)
    return result.reshape(B, nu * nx)

out = kronecker_rows(xs2, us)
print(out)

[[ 1  2  3 10 20 30]
 [12 15 18 28 35 42]]


In [59]:
Cs = np.random.randn(5, 5 * 3)
Cs_sep = Cs.reshape(5, 3, 5).transpose(1, 0, 2)

for i in range(3):
    assert np.allclose(Cs_sep[i], Cs[:, i * 5:(i + 1) * 5])

In [22]:
xs = np.array([[1, 2, 3],
               [1, 4, 8]])
ys = np.array([[4, 5, 6],
               [7, 8, 9]])

In [23]:
kron_results = np.einsum('bi,bj->bij', xs, ys).reshape(-1, 3 * 3)
print(kron_results)

[[ 4  5  6  8 10 12 12 15 18]
 [ 7  8  9 28 32 36 56 64 72]]
