In [19]:
import numpy as np
import matplotlib.pyplot as plt
from itertools import combinations_with_replacement
from functools import reduce
from operator import mul
from math import factorial

In [ ]:
def compute_monomial_observables_size(nx, order):
    return sum([
        factorial(nx + i - 1) / (factorial(i) * factorial(nx - 1)) for i in range(0, order+1)
    ])
    
def generate_monomial_observables(x, order):
    m = len(x)  # Number of original state variables
    monomials = [1]
    
    for j in range(1, order+1):
        for degrees in combinations_with_replacement(range(m), j):
            # Compute the product of the selected elements
            monomial = reduce(mul, [x[i] for i in degrees], 1)
            monomials.append(monomial)
    
    return np.array(monomials)

def generate_observable_matrices(X, order):
    N, _, nx = X.shape
    # observable_size = compute_monomial_observables_size(nx, order)
    
    M = np.empty_like(X)
    
    for i in range(N):
        M[i, 0, :] = generate_monomial_observables(X[i, 0, :], order)
        M[i, 1, :] = generate_monomial_observables(X[i, 1, :], order)
        
    A = M[:, 0, :]
    B = M[:, 1, :]
    
    return A, B

In [79]:
# Test method with known matrix
K = np.random.rand(3,3)
K = K.T @ K

N = 5
X = np.empty((N, 2, 3))
xs = np.random.rand(N, 3)

X[:, 0, :] = xs
X[:, 1, :] = (K @ xs.T).T

A = X[:, 0, :].T
B = X[:, 1, :].T

K_est = B @ np.linalg.pinv(A)
print("K estimated:\n", K_est)
print("K true:\n", K)

K estimated:
 [[1.00663527 0.54550047 0.56520401]
 [0.54550047 0.47999448 0.57097016]
 [0.56520401 0.57097016 0.77644767]]
K true:
 [[1.00663527 0.54550047 0.56520401]
 [0.54550047 0.47999448 0.57097016]
 [0.56520401 0.57097016 0.77644767]]
